### ISSUE TITLE
cannot import name 'Conformer' 

### ISSUE THREAD

**Issue by cyy857** [sooftware/conformer#32]
Hi when I tried to import conformer, I got this issue
`>>> from conformer import Conformer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/bert/conformer/conformer.py", line 3, in <module>
    from conformer import Conformer
ImportError: cannot import name 'Conformer' from partially initialized module 'conformer' (most likely due to a circular import) (/workspace/bert/conformer/conformer.py)
`
I did as the installation instruction. Would you please see where I might be wrong? Thanks.

**Comment by sooftware** [comment]
Maybe your environmental problem.   
How about `python3 setup.py install`?
